[package]
name = "kube-acme-cert-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "^0.8.8", features = ["macros"]}
kube = {version ="^3.0.1", default-features = false, features = [
    "kube-runtime", "runtime", "derive", "kube-derive", "client", "config",
    "rustls-tls", "aws-lc-rs"
]}
rustls = { version = "^0.23.38", default-features = false, features = [
    "std", "logging", "prefer-post-quantum", "aws-lc-rs"
]}

tokio = { version = "^1.50.0", features = ["full"] }
k8s-openapi = {version = "^0.27.1", default-features = false, features = ["schemars"]}
schemars = "^1.2.1"
serde = { version = "^1.0.228", features = ["derive"] }
serde_json = "^1.0.149"
thiserror = "^2.0.18"
futures = "0.3.32"
hyper = "1.8.1"
hyper-util = "0.1.20"
http = "1.4.0"
reqwest = {version = "0.13.2", default-features = false, features = [
    "charset",  "http2", "rustls"
]}
http-body-util = "0.1.3"

[features]
default = ["v1_35"]

v1_31=["k8s-openapi/v1_31"]
v1_32=["k8s-openapi/v1_32"]
v1_33=["k8s-openapi/v1_33"]
v1_34=["k8s-openapi/v1_34"]
v1_35=["k8s-openapi/v1_35"]

# TODO: fips may introduce extra build requirements, incluidng cmake and go installations
# fips=[
#     "rustls/fips",
# ]